<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="Crud_using_Gridview.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="Prod_Id" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" ShowFooter="True">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:TemplateField HeaderText="Prod_Id" InsertVisible="False" SortExpression="Prod_Id">
                        <EditItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# Eval("Prod_Id") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# Bind("Prod_Id") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:LinkButton  ID="LinkButton1" OnClick="LinkButton1_Click" ValidationGroup="insert" ForeColor="White" runat="server">Insert</asp:LinkButton>
                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Prod_name" SortExpression="Prod_name">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Prod_name") %>'></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" ForeColor="Red" SetFocusOnError="true" ControlToValidate="TextBox1" runat="server" ErrorMessage="Name Filed is Required" Text="*"></asp:RequiredFieldValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label2" runat="server" Text='<%# Bind("Prod_name") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="footerProductName" runat="server"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" ValidationGroup="insert" ForeColor="Red" SetFocusOnError="true" ControlToValidate="footerProductName" runat="server" ErrorMessage="Name Filed is Required" Text="*"></asp:RequiredFieldValidator>

                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Prod_Price" SortExpression="Prod_Price">

                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("Prod_Price") %>'></asp:TextBox>
                         <asp:RequiredFieldValidator ID="RequiredFieldValidator3" ForeColor="Red" SetFocusOnError="true" ControlToValidate="TextBox2" runat="server" ErrorMessage="Prod_Price Filed is Required" Text="*"></asp:RequiredFieldValidator>

                            </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label3" runat="server" Text='<%# Bind("Prod_Price") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="footerPrice" runat="server"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator4" ValidationGroup="insert" ForeColor="Red" SetFocusOnError="true" ControlToValidate="footerPrice" runat="server" ErrorMessage="Prod_Price Filed is Required" Text="*"></asp:RequiredFieldValidator>

                            
                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Prod_catagory" SortExpression="Prod_catagory">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("Prod_catagory") %>'></asp:TextBox>
                     <asp:RequiredFieldValidator ID="RequiredFieldValidator5" ForeColor="Red" SetFocusOnError="true" ControlToValidate="TextBox3" runat="server" ErrorMessage="Prod_catagory Filed is Required" Text="*"></asp:RequiredFieldValidator>

                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label4" runat="server" Text='<%# Bind("Prod_catagory") %>'></asp:Label>
                        </ItemTemplate>
                        <FooterTemplate>
                            <asp:TextBox ID="footerCatagory" runat="server"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator6" ValidationGroup="insert" ForeColor="Red" SetFocusOnError="true" ControlToValidate="footerCatagory" runat="server" ErrorMessage="Prod_catagory Filed is Required" Text="*"></asp:RequiredFieldValidator>

                        </FooterTemplate>
                    </asp:TemplateField>
                </Columns>
                <EditRowStyle BackColor="#7C6F57" />
                <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#E3EAEB" />
                <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F8FAFA" />
                <SortedAscendingHeaderStyle BackColor="#246B61" />
                <SortedDescendingCellStyle BackColor="#D4DFE1" />
                <SortedDescendingHeaderStyle BackColor="#15524A" />
            </asp:GridView>
            <asp:ValidationSummary ID="ValidationSummary1" ValidationGroup="insert" runat="server" BackColor="#CCCCCC" Font-Size="Larger" ForeColor="Red" />
            <asp:ValidationSummary ID="ValidationSummary2" runat="server" BackColor="#CCCCCC" Font-Size="Larger" ForeColor="Red" />

            <br />
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Product] WHERE [Prod_Id] = @Prod_Id" InsertCommand="INSERT INTO [Product] ([Prod_name], [Prod_Price], [Prod_catagory]) VALUES (@Prod_name, @Prod_Price, @Prod_catagory)" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [Product]" UpdateCommand="UPDATE [Product] SET [Prod_name] = @Prod_name, [Prod_Price] = @Prod_Price, [Prod_catagory] = @Prod_catagory WHERE [Prod_Id] = @Prod_Id">
                <DeleteParameters>
                    <asp:Parameter Name="Prod_Id" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="Prod_name" Type="String" />
                    <asp:Parameter Name="Prod_Price" Type="Decimal" />
                    <asp:Parameter Name="Prod_catagory" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Prod_name" Type="String" />
                    <asp:Parameter Name="Prod_Price" Type="Decimal" />
                    <asp:Parameter Name="Prod_catagory" Type="String" />
                    <asp:Parameter Name="Prod_Id" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </div>
    </form>
</body>
</html>
